home:
  - .zshrc
  - .sdlc.json
  - cloud-init.yaml
  - .skhdrc
  - .oh-my-posh-theme.json
  - .aerospace.toml
  - .config:
      - testVal;
      - yazi:
          - yazi.toml
          - keypad.toml
          - theme.toml
      - fish;
      - nvim;
      - zed;
      - tmux:
          - tmux.conf
